### ISSUE TITLE
only home page included in sitemap

### ISSUE THREAD

**Issue by laz0rama** [alexfinnarn/backdrop-xml-sitemap#45]
hello,
i have installed the current version of this module, and configured it accordingly.

my site has about 100,000 nodes (all but one of custom node types), about 15,000 published. when i generate the sitemap, the home page is the only url in the single generated file.  

i went into the database and saw only one row in the xmlsitemap table with a value of 1 for the "access" and "status" columns; all the rest had 0 for both of those columns. i updated both columns to 1 for many of the rows, and regenerated the sitemap. it looks to have worked.

so i guess my question is: why would all those rows have zero for the status and access columns, even though the nodes are published on the site? is this a bug, or have i missed something in the details?

thanks much for the module, regardless!

**Comment by laz0rama** [comment]
followup: it appears the sitemap generation still did not work after all. it processed all the nodes, and while it was processing i saw 3 files in the cache directory, with lots of good urls. but when i went back to look after processing was complete, there was a single xml file in the cache dir, with just the home page urls (/ and /home). same as what shows on the /admin/config/search/xmlsitemap page. 

also, after processing, in the xmlsitemap table the status is still 1, but the access column was set back to 0, except for the home page urls.

i hope that helps some.

**Comment by alexfinnarn** [comment]
Hey @laz0rama , thanks for reporting! When you first install the XML Sitemap module it only installs the main one by default. Because you can't assume a user wants to publish all nodes on their site when the module is first enabled, several other "helper" modules are used for adding nodes, menus, taxonomies, etc. to the sitemap. 

When I installed the module, I saw the same thing as you; however, when I enabled the `xmlsitemap_node` module, set the "Page" content type to included, and regenerated the links, I now saw more nodes in the sitemap than the front page.

Can you check which sitemap modules you have enabled and what the exclusion/inclusion settings are on "admin/config/search/xmlsitemap/settings".

Since this is a port from D7, I'm not entirely sure why all of the nodes are indexed, but if I had to guess, doing it this way reduces load on cron run if you are including/excluding the entities often enough...or some reason like that.

**Comment by laz0rama** [comment]
yes, i did see all the additional modules, which i had enabled. i have all the submodules enabled except menu and user. as for settings, in the "content" tab at the bottom i have all content types included.

does that answer your questions well enough? is there any other info i can provide to help?

**Comment by alexfinnarn** [comment]
I'm not sure what to say other than that and also not sure what else to ask for as far as settings go. I don't have 100,000 nodes, but my sitemap looks like it should. You could try enabling the menu module to debug further and add a menu or two to see if anything more shows up. Also check dblog for any messages around when you try and regenerate the sitemap.

Also, someone else made a smaller XML Sitemap module since this suite is huge https://github.com/backdrop-contrib/easy_xmlsitemap. Not sure if that module would fit your needs.

**Comment by laz0rama** [comment]
i have created my own super simple module to generate sitemap files, and it works fine. no settings, just a brute-force generation of as many files as are necessary. so i'll just use that for now. 

thanks anyway!
