### ISSUE TITLE
Move XMLsitemap settings page to 'Metadata' section of config menu?

### ISSUE THREAD

**Issue by jenlampton** [alexfinnarn/backdrop-xml-sitemap#50]
In backdrop we split the "Search" from "Metadata" in the configuration menu. Should we move the settings page for XMLsitemap to Metadata? Or do people feel like it has more to do with search?

**Comment by alexfinnarn** [comment]
The pages are indexed, which sounds like search terminology, and help people search for your site so I think leaving it in "Search" is fine.

I don't see a metadata section in the UI either...and since people would be looking for it in "Search" coming from Drupal, I don't think there is a great reason to move it to another menu.

**Comment by jenlampton** [comment]
> I don't see a metadata section in the UI

It's like User Interface, hidden until a contrib module uses it. I'm fine with leaving XMLSitemap where it is.
