### ISSUE TITLE
XML Sitemap Engines Failed Tests

### ISSUE THREAD

**Issue by alexfinnarn** [alexfinnarn/backdrop-xml-sitemap#59]
Fails on xmlsitemap_engines.test line #34

**Comment by quicksketch** [comment]
The failing engines test seems to have been caused by some incorrect tracking of watchdog messages. While all messages were being logged correctly, the XML Sitemap test methods for checking the messages weren't being reset in between each test, so the messages were colliding with each other. This has been fixed in https://github.com/backdrop-contrib/xmlsitemap/pull/107.
