### ISSUE TITLE
default setting for content type overrides setting per node

### ISSUE THREAD

**Issue by robertgarrigos** [alexfinnarn/backdrop-xml-sitemap#61]
The setting per node doesn't get saved. Default setting per content type is always in use for all nodes of that type.

To check this: go to a node and change its setting for site map inclusion and save it. Edit again and you will see it's not getting saved.

**Comment by alexfinnarn** [comment]
Hey @robertgarrigos. Thanks for catching this. I can confirm that this is an issue with the 1.0.3 security release update.

In that code change, what happened when a node was updated was queued and processed during a cr0on job run. Due to that change, the exclusion doesn't work.

This is also a problem in the Drupal module currently: https://www.drupal.org/project/xmlsitemap/issues/2987125

I will work on a fix based on that thread.

**Comment by alexfinnarn** [comment]
@robertgarrigos do you think you can test the attached PR? It is the same proposed solution in the Drupal 7 module. I think it is a bit kludgy, but I can't think of another way to do it yet.

**Comment by robertgarrigos** [comment]
yep, fixed with this pr for me

**Comment by robertgarrigos** [comment]
I have to reopen this because although the setting is being saved, the node is not being shown in the sitemap. You can check at the settings page, in the content list, that there are posts which are listed as indexed but not visible, as if they were unpublished. But they are published but marked as not visible. Is this related to this same error?

**Comment by alexfinnarn** [comment]
I will look at this, but one change made in the code was to run the checks on cron instead of node_upate. The PR for this issue marks the configuration on the individual node, but the inclusion/exclusion check happens during cron. 

Are you saying the node is still not visible after you have updated the node and cron has run? Or I guess you can manually regenerate the sitemap from the settings page to test as well...it'd be good to test both ways.

**Comment by robertgarrigos** [comment]
I've tested it both ways with no luck

**Comment by alexfinnarn** [comment]
@robertgarrigos Can you confirm that "Minimum sitemap lifetime" is set to "No minimum" at "admin/config/search/xmlsitemap/settings"?

![screen shot 2018-07-30 at 10 52 54 am](https://user-images.githubusercontent.com/3640707/43411214-c48df684-93e6-11e8-8f1c-f1193beb75b9.png)

I've tried excluding a node from an included content type, running cron, excluding the same node, running cron, and then doing those things a few more times. I end up seeing the changes reflected after the cron runs.

Maybe you have that variable set to something else that no minimum?

**Comment by robertgarrigos** [comment]
I see were the problem was: cron wasn't really working. I had to force cron with elysia. Thanks. Fixed.

**Comment by alexfinnarn** [comment]
Cool, and thanks for testing. I will make a release soon with the updated fixes.
