### ISSUE TITLE
Move some settings from config system to state system

### ISSUE THREAD

**Issue by jenlampton** [alexfinnarn/backdrop-xml-sitemap#83]
Every time I do a config sync, I show my xmlsitemap config file has changed. Usually, this is because the `engines_submit_last` value has been updated. This should probably be stored in state, instead of config, to prevent this problem.

**Comment by opi** [comment]
Same as https://github.com/backdrop-contrib/backup_migrate/issues/43 , so the corresponding PR could help finding inspiration : https://github.com/backdrop-contrib/backup_migrate/pull/44/files

Steps:
- [ ] Use `state_set()`/`state_get()` instead of `config_set()`/`config_get()`
- [ ] Implements a [`hook_update_N`](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_update_N/1) to get config value (`config_get()`) and save in state (`state_set()`)
- [ ] Remove existing key from config with `config_clear()`

**Comment by herbdool** [comment]
I took a look at this. Seems that there are other variables that should also be in the state system and removed from config: `generated_last`, `regenerate_needed`, `rebuild_needed`. It also means `xmlsitemap_var` should probably be removed since it can't be used for both state and config, and the todo on the function mentions it's not needed.

**Comment by herbdool** [comment]
A PR https://github.com/backdrop-contrib/xmlsitemap/pull/85. Please do some manually testing. Not all the tests are passing but I'm not sure if they were passing before. That could use work regardless to ensure the changes here don't break anything.

**Comment by herbdool** [comment]
I ran the tests *without* this PR and many of the same things are failing, so this PR doesn't make it any worse at least.

**Comment by jenlampton** [comment]
I'm applying this patch to a few of my site, and will test in production. It's been working great so far on a few tests sites.

**Comment by herbdool** [comment]
@laryn I could probably merge this pr if you're okay with it.

**Comment by laryn** [comment]
@herbdool I haven't run into any issues with it, not sure if @jenlampton has any further feedback.

**Comment by herbdool** [comment]
@laryn so that's an ok, I can merge this? You want to make a release or can I?

**Comment by laryn** [comment]
Oy, completely forgot I had become maintainer of this module. I was thinking, why does he keep asking me? 🥴

Yes, go ahead @herbdool , or I will try to do it when I'm by the computer later today.

**Comment by jenlampton** [comment]
I have no further feedback, patch still working like a charm. Thank you both!

**Comment by herbdool** [comment]
I've merged and released!
